### ISSUE TITLE
Supplementary

### ISSUE THREAD

**Issue by csyhping** [PhyRecon/PhyRecon#1]
Hi @DaLi-Jack , thanks for your fantastic work. May I ask where can we find the supplementary?

**Comment by DaLi-Jack** [comment]
Hello! Thank you for your interest in our work!
We are preparing for submission. When the supplementary materials are ready, I will upload them to arXiv immediately and notify you in this issue.

**Comment by DaLi-Jack** [comment]
We have updated the paper with supplementary materials. Please check the latest version of the paper on arXiv.
